<?php

// Freistilbox blocks the 'config' directory.
$config_directories[CONFIG_SYNC_DIRECTORY] = '../config-sync';

// Drush language commands.
$settings['custom_translations_directory'] = '../custom/translations';

// Container yamls.
$settings['container_yamls'][] = $app_root . '/' . $site_path . '/services.yml';

// Hash salt. Generated by settings-init script.
$settings['hash_salt'] = require '../custom/hash_salt.php';

