pipeline:
  - name: Revert wodby's changes to settings, but don't fail if no file committed.
    command: git checkout HEAD `readlink docroot||echo docroot`/sites/default/settings.php||true
  - name: Composer install.
    command: composer install --no-dev --no-progress --optimize-autoloader --prefer-dist
  - name: Composer bin all install.
    command: '! composer help bin >/dev/null 2>/dev/null || composer bin all install --no-dev --no-progress --optimize-autoloader --prefer-dist'
  - name: Symlink our settings.
    command: ln -sf server-wodby.php settings/generated/server.php
  - name: Symlink our solr.
    command: ln -sf solr-wodby.php settings/generated/solr.php
  - name: Scaffold our siteurl.
    command: |
      { echo '<?php'; echo "return getenv('WODBY_URL_PRIMARY');"; } >settings/generated/local/siteurl.php
  - name: Update database
    command: drush -y updb --cache-clear=0
    directory: docroot
    only_if: test "$(drush status --fields=bootstrap)"
  - name: Enable master
    command: drush -y en master || true
    directory: docroot
    only_if: test "$(drush status --fields=bootstrap)"
  - name: Master-exec
    command: '! drush help master-exec >/dev/null 2>/dev/null || drush -y master-exec'
    directory: docroot
    only_if: test "$(drush status --fields=bootstrap)"
  - name: Revert features, if possible.
    command: '! drush help fra >/dev/null 2>/dev/null || drush -y fra'
    directory: docroot
    only_if: test "$(drush status --fields=bootstrap)"
  - name: Refresh languages, if possible
    command: '! drush help language-refresh >/dev/null 2>/dev/null || drush -y language-refresh'
    directory: docroot
    only_if: test "$(drush status --fields=bootstrap)"
  - name: clear cache
    command: drush cc all
    directory: docroot
    only_if: test "$(drush status --fields=bootstrap)"

