pipeline:
  - name: Revert wodby's changes to settings
    command: git checkout HEAD `readlink -f docroot/sites/default/settings.php`
  - name: Composer install.
    command: composer install --no-progress --optimize-autoloader --prefer-dist
  - name: Symlink our settings.
    command: ln -sf server-wodby.php settings/server.php
  - name: Symlink our solr.
    command: ln -sf solr-wodby.php settings/solr.php
  - name: Update database
    command: drush -y updb
    directory: docroot
    only_if: test "$(drush status --fields=bootstrap)"
  - name: Import config
    command: drush -y cim
    directory: docroot
    only_if: test "$(drush status --fields=bootstrap)" && test -f ../config-sync/core.extension.yml

